@extends('layouts.master')
@section('title','Promotions')
@section('content')
<div class="toolbar"><div class="container-fluid d-flex justify-content-between"><div><h1 class="fs-3 fw-bold mb-1">Promotions</h1><div class="text-muted">Manage employee promotions and career advancements.</div></div><button class="btn btn-sm btn-success" type="button" onclick="openPromotion('create')">＋ Add Promotion</button></div></div>
<div class="container-fluid py-6 promotion-page">
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="card promotion-filter"><form method="GET"><div class="promotion-search"><svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg><input name="search" value="{{ request('search') }}" placeholder="Search..."></div><select name="designation_id"><option value="">All Designations</option>@foreach($designations as $designation)<option value="{{ $designation->id }}" @selected(request('designation_id')==$designation->id)>{{ $designation->name }}</option>@endforeach</select><input type="date" name="from" value="{{ request('from') }}"><input type="date" name="to" value="{{ request('to') }}"><input type="hidden" name="status" value="{{ request('status','All') }}"><button class="btn filter-button">⌄ Filters</button>@if(request()->hasAny(['search','designation_id','from','to']))<a class="btn danger" href="{{ route('promotion-index') }}">Clear</a>@endif</form><div class="promotion-tabs">@foreach($counts as $status=>$count)<a class="{{ request('status','All')===$status?'active':'' }}" href="{{ route('promotion-index',array_filter(request()->except(['page','status'])+($status==='All'?[]:['status'=>$status]))) }}">{{ $status }} <b>{{ $count }}</b></a>@endforeach</div></div>
<div class="card promotion-card"><div class="table-wrap"><table class="table promotion-table"><thead><tr><th>#</th><th>Employee</th><th>Previous Designation</th><th>New Designation</th><th>Promotion Date</th><th>Effective Date</th><th>Status</th><th>Document</th><th>Actions</th></tr></thead><tbody>
@forelse($promotions as $promotion)@php($payload=['id'=>$promotion->id,'employee_id'=>$promotion->employee_id,'employee_name'=>$promotion->employee?->name,'employee_email'=>$promotion->employee?->email,'previous_designation_id'=>$promotion->previous_designation_id,'previous_designation'=>$promotion->previousDesignation?->name,'new_designation_id'=>$promotion->new_designation_id,'new_designation'=>$promotion->newDesignation?->name,'promotion_date'=>$promotion->promotion_date?->format('Y-m-d'),'effective_date'=>$promotion->effective_date?->format('Y-m-d'),'reason'=>$promotion->reason,'status'=>$promotion->status,'document_path'=>$promotion->document_path])<tr><td>{{ $promotions->firstItem()+$loop->index }}</td><td><div class="promotion-person">@if($promotion->employee?->profile_image)<img class="promotion-avatar" src="{{ route('employee-profile',$promotion->employee) }}">@else<span class="promotion-avatar"></span>@endif<div><strong>{{ $promotion->employee?->name??'—' }}</strong><small>{{ $promotion->employee?->email??'—' }}</small></div></div></td><td>{{ $promotion->previousDesignation?->name??'—' }}</td><td>{{ $promotion->newDesignation?->name??'—' }}</td><td><svg class="promotion-calendar-icon" viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/></svg>{{ $promotion->promotion_date?->format('Y-m-d') }}</td><td><svg class="promotion-calendar-icon" viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/></svg>{{ $promotion->effective_date?->format('Y-m-d') }}</td><td><span class="promotion-status {{ strtolower($promotion->status) }}">{{ $promotion->status }}</span></td><td>@if($promotion->document_path)<a href="{{ route('promotion-document',$promotion) }}" target="_blank">▤</a>@else — @endif</td><td><div class="promotion-actions"><button title="View" data-item="{{ base64_encode(json_encode($payload)) }}" onclick="viewPromotion(this.dataset.item)"><svg viewBox="0 0 24 24"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z"/><circle cx="12" cy="12" r="2.5"/></svg></button><button title="Edit" data-item="{{ base64_encode(json_encode($payload)) }}" onclick="openPromotion('edit',this.dataset.item)"><svg viewBox="0 0 24 24"><path d="M12 20H5a1 1 0 0 1-1-1v-7"/><path d="m16.5 3.5 4 4L11 17l-5 1 1-5Z"/></svg></button><button title="Status" data-id="{{ $promotion->id }}" data-status="{{ $promotion->status }}" onclick="openStatus(this.dataset.id,this.dataset.status)"><svg viewBox="0 0 24 24"><path d="M20 11a8 8 0 1 0-2.3 5.7"/><path d="M20 4v7h-7"/></svg></button><form method="POST" action="{{ route('promotion-destroy',$promotion) }}" onsubmit="return confirm('Delete this promotion?')">@csrf @method('DELETE')<button title="Delete"><svg viewBox="0 0 24 24"><path d="M3 6h18M8 6V4h8v2m3 0-1 15H6L5 6m5 4v7m4-7v7"/></svg></button></form></div></td></tr>@empty<tr><td colspan="9">No promotions found.</td></tr>@endforelse
</tbody></table></div><div class="promotion-footer"><span>Showing {{ $promotions->firstItem()??0 }} to {{ $promotions->lastItem()??0 }} of {{ $promotions->total() }} results</span><div>{{ $promotions->onEachSide(1)->links('pagination::bootstrap-4') }}</div></div></div>
</div>

<div class="promotion-overlay" id="promotionModal"><div class="promotion-modal"><form id="promotionForm" method="POST" enctype="multipart/form-data" action="{{ route('promotion-store') }}" novalidate>@csrf<span id="promotionMethod"></span><div class="promotion-modal-head"><h2 id="promotionTitle">Add New Promotion</h2><button class="modal-close" type="button" onclick="closeModal('promotionModal')">×</button></div><div class="promotion-modal-body"><label>Employee <em>*</em><select name="employee_id"><option value="">Select employee</option>@foreach($employees as $employee)<option value="{{ $employee->id }}" data-designation="{{ $employee->designation_id }}">{{ $employee->name }} ({{ $employee->employee_code }})</option>@endforeach</select></label><label>Previous Designation <em>*</em><select name="previous_designation_id" disabled><option value="">Select previous designation</option>@foreach($designations as $designation)<option value="{{ $designation->id }}">{{ $designation->name }}</option>@endforeach</select></label><label>New Designation <em>*</em><select name="new_designation_id"><option value="">Select New Designation</option>@foreach($designations as $designation)<option value="{{ $designation->id }}">{{ $designation->name }}</option>@endforeach</select></label><label>Promotion Date <em>*</em><input type="date" name="promotion_date"></label><label>Effective Date <em>*</em><input type="date" name="effective_date"></label><label>Reason for Promotion<textarea name="reason" rows="3" placeholder="e.g. Exceptional performance and leadership skills..."></textarea></label><label>Document<input type="file" name="document" accept=".pdf,.jpg,.jpeg,.png,.doc,.docx"></label><label>Status <em>*</em><select name="status"><option>Pending</option><option>Approved</option><option>Rejected</option></select></label></div><div class="promotion-modal-footer"><button class="btn" type="button" onclick="closeModal('promotionModal')">Cancel</button><button class="btn primary">Save</button></div></form></div></div>

<div class="promotion-overlay" id="detailModal"><div class="promotion-modal wide"><div class="promotion-modal-head"><div class="promotion-detail-head"><span class="promotion-detail-icon">↗</span><h2>Promotion Details</h2></div><button class="modal-close" onclick="closeModal('detailModal')">×</button></div><div class="promotion-modal-body"><div class="promotion-employee-box"><span class="promotion-avatar"></span><div><span class="detail-label">Employee</span><strong data-detail="employee"></strong></div><span data-detail="status"></span></div><div class="designation-label">Designation Change</div><div class="designation-change"><div class="designation-box"><span class="detail-label">Previous</span><strong data-detail="previous"></strong></div><div class="designation-arrow">→</div><div class="designation-box new"><span class="detail-label">New</span><strong data-detail="new"></strong></div></div><div class="detail-label">Timeline</div><div class="timeline"><div><span class="detail-label">Promotion Date</span><strong data-detail="promotion_date"></strong></div><div><span class="detail-label">Effective Date</span><strong data-detail="effective_date"></strong></div></div><div data-detail="document"></div><div class="promotion-reason"><span class="detail-label">Reason for Promotion</span><div data-detail="reason"></div></div></div></div></div>

<div class="promotion-overlay" id="statusModal"><div class="promotion-modal" style="max-width:400px"><form id="statusForm" method="POST">@csrf @method('PATCH')<div class="promotion-modal-head"><h2>Update Promotion Status</h2><button class="modal-close" type="button" onclick="closeModal('statusModal')">×</button></div><div class="promotion-modal-body"><label>Status <em>*</em><select name="status"><option>Pending</option><option>Approved</option><option>Rejected</option></select></label></div><div class="promotion-modal-footer"><button class="btn" type="button" onclick="closeModal('statusModal')">Cancel</button><button class="btn primary">Save</button></div></form></div></div>

<script>
const promotionStore=@json(route('promotion-store')),promotionUpdate=@json(route('promotion-update','__ID__')),promotionStatus=@json(route('promotion-status','__ID__')),promotionDocument=@json(route('promotion-document','__ID__'));
function pdata(encoded){return encoded?JSON.parse(atob(encoded)):{};}function closeModal(id){document.getElementById(id).classList.remove('open')}function showModal(id){document.getElementById(id).classList.add('open')}
function openPromotion(mode,encoded){const f=document.getElementById('promotionForm'),d=pdata(encoded);f.reset();clearErrors(f);f.action=promotionStore;document.getElementById('promotionMethod').innerHTML='';document.getElementById('promotionTitle').textContent=mode==='edit'?'Edit Promotion':'Add New Promotion';['employee_id','new_designation_id','promotion_date','effective_date','reason','status'].forEach(k=>f.elements[k].value=d[k]|| (k==='status'?'Pending':''));f.elements.previous_designation_id.value=d.previous_designation_id||'';if(mode==='edit'){f.action=promotionUpdate.replace('__ID__',d.id);document.getElementById('promotionMethod').innerHTML='<input type="hidden" name="_method" value="PUT">'}showModal('promotionModal')}
function viewPromotion(encoded){const d=pdata(encoded),m=document.getElementById('detailModal');m.querySelector('[data-detail=employee]').textContent=d.employee_name||'—';m.querySelector('[data-detail=status]').innerHTML='<span class="promotion-status '+(d.status||'').toLowerCase()+'">'+(d.status||'—')+'</span>';m.querySelector('[data-detail=previous]').textContent=d.previous_designation||'—';m.querySelector('[data-detail=new]').textContent=d.new_designation||'—';m.querySelector('[data-detail=promotion_date]').textContent=d.promotion_date||'—';m.querySelector('[data-detail=effective_date]').textContent=d.effective_date||'—';m.querySelector('[data-detail=reason]').textContent=d.reason||'—';m.querySelector('[data-detail=document]').innerHTML=d.document_path?'<div class="detail-label">Document</div><a class="btn" target="_blank" href="'+promotionDocument.replace('__ID__',d.id)+'">View Document</a>':'';showModal('detailModal')}
function openStatus(id,status){const f=document.getElementById('statusForm');f.action=promotionStatus.replace('__ID__',id);f.elements.status.value=status;showModal('statusModal')}function clearErrors(f){f.querySelectorAll('.promotion-invalid').forEach(x=>x.classList.remove('promotion-invalid'));f.querySelectorAll('.promotion-error').forEach(x=>x.remove())}
document.addEventListener('DOMContentLoaded',function(){const f=document.getElementById('promotionForm'),employee=f.elements.employee_id;employee.addEventListener('change',()=>f.elements.previous_designation_id.value=employee.selectedOptions[0]?.dataset.designation||'');const rules={employee_id:x=>x.value?'':'Employee is required',new_designation_id:x=>x.value?'':'New Designation is required',promotion_date:x=>x.value?'':'Promotion Date is required',effective_date:x=>!x.value?'Effective Date is required':(f.elements.promotion_date.value&&x.value<f.elements.promotion_date.value?'Effective Date must be on or after Promotion Date':''),reason:x=>x.value.length>2000?'Reason may not exceed 2000 characters':'',document:x=>x.files[0]&&x.files[0].size>5242880?'Document may not exceed 5 MB':''};function valid(x){const msg=rules[x.name](x);let e=x.parentElement.querySelector('.promotion-error');if(!e){e=document.createElement('div');e.className='promotion-error';x.after(e)}x.classList.toggle('promotion-invalid',!!msg);e.textContent=msg;e.style.display=msg?'block':'none';return !msg}Object.keys(rules).forEach(n=>['input','change','blur'].forEach(ev=>f.elements[n].addEventListener(ev,()=>valid(f.elements[n]))));f.addEventListener('submit',function(e){let first=null;Object.keys(rules).forEach(n=>{if(!valid(f.elements[n])&&!first)first=f.elements[n]});if(first){e.preventDefault();first.focus()}});document.querySelectorAll('.promotion-overlay').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m.id)}))});
</script>
@endsection
