<?php
namespace App\Http\Controllers;use App\Models\{Employee,EmployeeReview,ReviewCycle,User};use Illuminate\Http\Request;
class EmployeeReviewController extends Controller{
 public function index(Request $r){$q=EmployeeReview::with(['employee','reviewer','cycle'])->latest('review_date');$q->when($r->search,fn($q,$v)=>$q->where(fn($x)=>$x->whereHas('employee',fn($e)=>$e->where('name','like',"%$v%")->orWhere('email','like',"%$v%"))->orWhereHas('reviewer',fn($u)=>$u->where('first_name','like',"%$v%")->orWhere('last_name','like',"%$v%"))))->when($r->review_cycle_id,fn($q,$v)=>$q->where('review_cycle_id',$v))->when($r->from,fn($q,$v)=>$q->whereDate('review_date','>=',$v))->when($r->to,fn($q,$v)=>$q->whereDate('review_date','<=',$v))->when($r->status&&$r->status!=='All',fn($q)=>$q->where('status',$r->status));$counts=['All'=>EmployeeReview::count(),'Scheduled'=>EmployeeReview::whereStatus('Scheduled')->count(),'In Progress'=>EmployeeReview::whereStatus('In Progress')->count(),'Completed'=>EmployeeReview::whereStatus('Completed')->count()];return view('employee-reviews.index',['reviews'=>$q->paginate(10)->withQueryString(),'cycles'=>ReviewCycle::whereStatus(1)->orderBy('name')->get(),'counts'=>$counts]);}
 public function create(){return view('employee-reviews.create',['employees'=>Employee::orderBy('name')->get(),'reviewers'=>User::where('status',1)->orderBy('first_name')->get(),'cycles'=>ReviewCycle::whereStatus(1)->orderBy('name')->get()]);}
 public function store(Request $r){EmployeeReview::create($r->validate(['employee_id'=>'required|exists:employees,id','reviewer_id'=>'required|exists:users,id','review_cycle_id'=>'required|exists:review_cycles,id','review_date'=>'required|date','status'=>'required|in:Scheduled,In Progress,Completed']));return redirect()->route('employee-reviews-index')->with('success','Employee review scheduled successfully.');}
 public function show(EmployeeReview $employeeReview){$employeeReview->load(['employee','reviewer','cycle']);return view('employee-reviews.show',['review'=>$employeeReview]);}
 public function conduct(EmployeeReview $employeeReview){$employeeReview->load(['employee','reviewer','cycle']);return view('employee-reviews.conduct',['review'=>$employeeReview,'indicators'=>$this->indicators()]);}
 public function saveConduct(Request $r,EmployeeReview $employeeReview){$keys=collect($this->indicators())->flatten(1)->pluck('key');$rules=['comments'=>'nullable|string|max:3000','action'=>'required|in:draft,complete'];foreach($keys as $key){$rules["ratings.$key.rating"]='required|numeric|min:0|max:5';$rules["ratings.$key.comments"]='nullable|string|max:1000';}$d=$r->validate($rules);$ratings=$d['ratings'];$average=round(collect($ratings)->avg(fn($x)=>(float)$x['rating']),1);$employeeReview->update(['ratings'=>$ratings,'rating'=>$average,'comments'=>$d['comments']??null,'status'=>$d['action']==='complete'?'Completed':'In Progress']);return redirect()->route('employee-reviews-show',$employeeReview)->with('success',$d['action']==='complete'?'Performance review completed successfully.':'Performance review saved successfully.');}
 public function status(Request $r,EmployeeReview $employeeReview){$d=$r->validate(['status'=>'required|in:Scheduled,In Progress,Completed','rating'=>'nullable|required_if:status,Completed|numeric|min:0|max:5','comments'=>'nullable|string|max:3000']);$employeeReview->update($d);return back()->with('success','Review status updated successfully.');}
 public function destroy(EmployeeReview $employeeReview){$employeeReview->delete();return back()->with('success','Employee review deleted.');}
 private function indicators():array{return ['Job Performance'=>[['key'=>'task_completion','name'=>'Task Completion Rate','description'=>'Percentage of assigned tasks completed within specified timeframes','type'=>'Percentage'],['key'=>'goal_achievement','name'=>'Goal Achievement','description'=>'Success rate in achieving individual and team objectives','type'=>'Percentage'],['key'=>'productivity','name'=>'Productivity Level','description'=>'Output efficiency compared to established benchmarks','type'=>'Rating']], 'Quality of Work'=>[['key'=>'error_rate','name'=>'Error Rate','description'=>'Frequency of mistakes or defects in work output','type'=>'Percentage'],['key'=>'accuracy','name'=>'Accuracy Level','description'=>'Precision and correctness in completing tasks and deliverables','type'=>'Percentage'],['key'=>'attention_detail','name'=>'Attention to Detail','description'=>'Thoroughness and care demonstrated in work','type'=>'Rating']], 'Professional Skills'=>[['key'=>'communication','name'=>'Communication Skills','description'=>'Effectiveness in written and verbal communication','type'=>'Rating'],['key'=>'teamwork','name'=>'Teamwork','description'=>'Collaboration and contribution to team goals','type'=>'Rating'],['key'=>'problem_solving','name'=>'Problem Solving','description'=>'Ability to identify and resolve workplace challenges','type'=>'Rating']], 'Reliability and Growth'=>[['key'=>'attendance','name'=>'Attendance & Punctuality','description'=>'Consistency in attendance and meeting schedules','type'=>'Percentage'],['key'=>'initiative','name'=>'Initiative','description'=>'Proactive approach and willingness to take responsibility','type'=>'Rating'],['key'=>'development','name'=>'Professional Development','description'=>'Commitment to learning and improving skills','type'=>'Rating']]];}
}
