<?php
namespace App\Http\Controllers;
use App\Models\OrganizationItem;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
class OrganizationController extends Controller {
 private array $types=['branches'=>'Branches','departments'=>'Departments','designations'=>'Designations','holidays'=>'Holidays','announcements'=>'Announcements','award-types'=>'Award Types','shifts'=>'Shifts','attendance-policies'=>'Attendance Policies','document-types'=>'Document Types'];
 public function __construct(){ $this->middleware('auth'); }
 public function branches(Request $r){return $this->index($r,'branches');} public function departments(Request $r){return $this->index($r,'departments');}
 public function designations(Request $r){return $this->index($r,'designations');} public function shifts(Request $r){return $this->index($r,'shifts');}
 public function attendancePolicies(Request $r){return $this->index($r,'attendance-policies');} public function documentTypes(Request $r){return $this->index($r,'document-types');}
 public function holidays(Request $r){return $this->index($r,'holidays');} public function announcements(Request $r){return $this->index($r,'announcements');} public function awardTypes(Request $r){return $this->index($r,'award-types');}
 private function table(string $type):string{abort_unless(isset($this->types[$type]),404);return str_replace('-','_',$type);}
 public function index(Request $r,string $type){$table=$this->table($type);$query=DB::table($table);if($type==='branches')$query->select('*','branch_name as name','branch_code as code');$query->when($r->search,fn($q,$s)=>$q->where($type==='branches'?'branch_name':'name','like',"%$s%"))->when($r->status!==null&&$r->status!=='',fn($q)=>$q->where('status',$r->status));if($type==='departments'&&$r->branch_id)$query->where('branch_id',$r->branch_id);if($type==='designations'&&$r->department_id)$query->where('department_id',$r->department_id);$items=$query->latest()->paginate(10)->withQueryString();return view('organization.index',['type'=>$type,'title'=>$this->types[$type],'items'=>$items,'branches'=>DB::table('branches')->where('status',1)->select('id','branch_name as name')->get(),'departments'=>DB::table('departments')->where('status',1)->get(),'allCount'=>DB::table($table)->count(),'activeCount'=>DB::table($table)->where('status',1)->count(),'inactiveCount'=>DB::table($table)->where('status',0)->count()]);}
 public function create(string $type){$this->table($type);return view('organization.form',['type'=>$type,'title'=>$this->types[$type],'item'=>null,'branches'=>DB::table('branches')->where('status',1)->select('id','branch_name as name')->get(),'departments'=>DB::table('departments')->where('status',1)->get()]);}
 public function edit(string $type,int $id){$table=$this->table($type);$item=DB::table($table)->find($id);if($type==='branches'){$item->name=$item->branch_name;$item->code=$item->branch_code;}return view('organization.form',['type'=>$type,'title'=>$this->types[$type],'item'=>$item,'branches'=>DB::table('branches')->where('status',1)->select('id','branch_name as name')->get(),'departments'=>DB::table('departments')->where('status',1)->get()]);}
 public function store(Request $r,string $type){$table=$this->table($type);DB::table($table)->insert($this->data($r,$type)+['created_at'=>now(),'updated_at'=>now()]);return redirect()->route('organization.index',$type)->with('success','Created successfully.');}
 public function update(Request $r,string $type,int $id){DB::table($this->table($type))->where('id',$id)->update($this->data($r,$type,$id)+['updated_at'=>now()]);return redirect()->route('organization.index',$type)->with('success','Updated successfully.');}
 public function destroy(string $type,int $id){DB::table($this->table($type))->where('id',$id)->delete();return back()->with('success','Deleted successfully.');}
 private function data(Request $r,string $type,?int $id=null):array{$r->merge(['name'=>trim((string)$r->input('name'))]);$nameRules=['required','string','min:2','max:100','regex:/^[\pL\pM0-9 .&()\'\/-]+$/u'];$codeRules=['nullable','string','max:50'];if($type==='branches'){$nameRules[]=Rule::unique('branches','branch_name')->ignore($id);$codeRules[]='regex:/^[A-Za-z0-9_-]+$/';$codeRules[]=Rule::unique('branches','branch_code')->ignore($id);}$data=$r->validate(['name'=>$nameRules,'code'=>$codeRules,'status'=>'required|boolean','email'=>'nullable|email','contact'=>'nullable|max:50','branch_id'=>'nullable|exists:branches,id','department_id'=>'nullable|exists:departments,id','start_time'=>'nullable','end_time'=>'nullable','late_after_minutes'=>'nullable|integer|min:0','working_hours'=>'nullable|numeric|min:0','holiday_date'=>'nullable|date','category'=>'nullable|max:100','description'=>'nullable|string','start_date'=>'nullable|date','end_date'=>'nullable|date','audience'=>'nullable|max:100','is_required'=>'nullable|boolean'],['name.required'=>'Branch name is required.','name.min'=>'Branch name must be at least 2 characters.','name.max'=>'Branch name may not be greater than 100 characters.','name.regex'=>'Branch name contains invalid characters.','name.unique'=>'This branch name already exists.','code.regex'=>'Branch code may contain letters, numbers, dash and underscore only.','code.unique'=>'This branch code already exists.']);if($type==='branches'){$data['branch_name']=$data['name'];$data['branch_code']=filled($data['code']??null)?strtoupper($data['code']):($id?DB::table('branches')->where('id',$id)->value('branch_code'):$this->nextBranchCode());unset($data['name'],$data['code']);}return array_filter($data,fn($v,$k)=>in_array($k,DB::getSchemaBuilder()->getColumnListing($this->table($type)))&&$v!==null,ARRAY_FILTER_USE_BOTH);}
 private function nextBranchCode():string{$number=(int)DB::table('branches')->max('id')+1;do{$code='BR-'.str_pad((string)$number++,5,'0',STR_PAD_LEFT);}while(DB::table('branches')->where('branch_code',$code)->exists());return $code;}
}
