<?php
namespace App\Http\Controllers;
use App\Models\{Employee,EmployeeTermination,TerminationType};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
class TerminationController extends Controller{
 public function index(Request $r){$q=EmployeeTermination::with(['employee','type'])->latest('termination_date');$q->when($r->search,fn($q,$v)=>$q->whereHas('employee',fn($e)=>$e->where('name','like',"%$v%")->orWhere('email','like',"%$v%")))->when($r->termination_type_id,fn($q,$v)=>$q->where('termination_type_id',$v))->when($r->from,fn($q,$v)=>$q->whereDate('termination_date','>=',$v))->when($r->to,fn($q,$v)=>$q->whereDate('termination_date','<=',$v))->when($r->status&&$r->status!=='All',fn($q)=>$q->where('status',$r->status));$counts=['All'=>EmployeeTermination::count(),'Planned'=>EmployeeTermination::whereStatus('Planned')->count(),'In Progress'=>EmployeeTermination::whereStatus('In Progress')->count(),'Completed'=>EmployeeTermination::whereStatus('Completed')->count()];return view('terminations.index',['terminations'=>$q->paginate(10)->withQueryString(),'employees'=>Employee::orderBy('name')->get(),'types'=>TerminationType::whereStatus(true)->orderBy('name')->get(),'counts'=>$counts]);}
 public function store(Request $r){$this->save($r,new EmployeeTermination);return back()->with('success','Termination created.');}
 public function update(Request $r,EmployeeTermination $termination){$this->save($r,$termination);if($termination->status==='Completed')$termination->employee()->update(['employment_status'=>'Inactive','login_status'=>0]);return back()->with('success','Termination updated.');}
 public function status(Request $r,EmployeeTermination $termination){$d=$r->validate(['status'=>'required|in:Planned,In Progress,Completed','exit_interview_conducted'=>'nullable|boolean','exit_interview_date'=>'nullable|date','exit_feedback'=>'nullable|string|max:2000']);$d['exit_interview_conducted']=$r->boolean('exit_interview_conducted');$termination->update($d);if($d['status']==='Completed')$termination->employee()->update(['employment_status'=>'Inactive','login_status'=>0]);return back()->with('success','Termination status updated.');}
 public function document(EmployeeTermination $termination){abort_unless($termination->document_path&&Storage::disk('public')->exists($termination->document_path),404);return Storage::disk('public')->response($termination->document_path);}
 public function destroy(EmployeeTermination $termination){if($termination->document_path)Storage::disk('public')->delete($termination->document_path);$termination->delete();return back()->with('success','Termination deleted.');}
 private function save(Request $r,EmployeeTermination $x):void{$d=$r->validate(['employee_id'=>'required|exists:employees,id','termination_type_id'=>'required|exists:termination_types,id','notice_date'=>'required|date','termination_date'=>'required|date|after_or_equal:notice_date','notice_period'=>'nullable|string|max:50','reason'=>'required|string|max:191','description'=>'nullable|string|max:3000','document'=>'nullable|file|mimes:pdf,jpg,jpeg,png,doc,docx|max:5120','status'=>'nullable|in:Planned,In Progress,Completed','exit_interview_conducted'=>'nullable|boolean','exit_interview_date'=>'nullable|date','exit_feedback'=>'nullable|string|max:2000','remove_document'=>'nullable|boolean']);unset($d['document'],$d['remove_document']);if($r->boolean('remove_document')&&$x->document_path){Storage::disk('public')->delete($x->document_path);$d['document_path']=null;}if($r->hasFile('document')){if($x->document_path)Storage::disk('public')->delete($x->document_path);$d['document_path']=$r->file('document')->store('terminations','public');}$d['exit_interview_conducted']=$r->boolean('exit_interview_conducted');$x->fill($d)->save();}
}
