<?php
namespace App\Http\Controllers;
use App\Models\{Branch,Department,Designation,Employee,EmployeeTransfer};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\{DB,Storage};
class TransferController extends Controller{
 public function __construct(){$this->middleware('auth');}
 public function index(Request $r){$q=EmployeeTransfer::with(['employee','fromBranch','toBranch','fromDepartment','toDepartment','fromDesignation','toDesignation'])->latest('transfer_date');$q->when($r->search,fn($q,$v)=>$q->whereHas('employee',fn($e)=>$e->where('name','like',"%$v%")->orWhere('email','like',"%$v%")))->when($r->department_id,fn($q,$v)=>$q->where('to_department_id',$v))->when($r->from,fn($q,$v)=>$q->whereDate('transfer_date','>=',$v))->when($r->to,fn($q,$v)=>$q->whereDate('transfer_date','<=',$v))->when($r->status&&$r->status!=='All',fn($q)=>$q->where('status',$r->status));$counts=['All'=>EmployeeTransfer::count(),'Pending'=>EmployeeTransfer::whereStatus('Pending')->count(),'Approved'=>EmployeeTransfer::whereStatus('Approved')->count(),'Rejected'=>EmployeeTransfer::whereStatus('Rejected')->count()];return view('transfers.index',['transfers'=>$q->paginate(10)->withQueryString(),'employees'=>Employee::where('employment_status','Active')->orderBy('name')->get(),'branches'=>Branch::where('status',1)->orderBy('branch_name')->get(),'departments'=>Department::where('status',1)->orderBy('name')->get(),'designations'=>Designation::where('status',1)->orderBy('name')->get(),'counts'=>$counts]);}
 public function store(Request $r){$this->save($r,new EmployeeTransfer);return back()->with('success','Transfer created successfully.');}
 public function update(Request $r,EmployeeTransfer $transfer){$this->save($r,$transfer);return back()->with('success','Transfer updated successfully.');}
 public function status(Request $r,EmployeeTransfer $transfer){$d=$r->validate(['status'=>'required|in:Pending,Approved,Rejected','notes'=>['nullable','string','max:2000',function($a,$v,$fail)use($r){if($r->status==='Rejected'&&!trim((string)$v))$fail('Rejection Reason is required.');}]]);DB::transaction(function()use($transfer,$d){$transfer->update($d);$this->applyIfApproved($transfer);});return back()->with('success',$d['status']==='Approved'?'Transfer approved successfully.':'Transfer rejected successfully.');}
 public function destroy(EmployeeTransfer $transfer){if($transfer->document_path)Storage::disk('public')->delete($transfer->document_path);$transfer->delete();return back()->with('success','Transfer deleted successfully.');}
 public function document(EmployeeTransfer $transfer){abort_unless($transfer->document_path&&Storage::disk('public')->exists($transfer->document_path),404);return Storage::disk('public')->response($transfer->document_path);}
 private function save(Request $r,EmployeeTransfer $t):void{$d=$r->validate(['employee_id'=>'required|exists:employees,id','to_branch_id'=>'required|exists:branches,id','to_department_id'=>'required|exists:departments,id','to_designation_id'=>'nullable|exists:designations,id','transfer_date'=>'required|date','effective_date'=>'required|date|after_or_equal:transfer_date','reason'=>'required|string|max:2000','document'=>'nullable|file|mimes:pdf,jpg,jpeg,png,doc,docx|max:5120','status'=>'required|in:Pending,Approved,Rejected','notes'=>'nullable|string|max:2000']);$e=Employee::findOrFail($d['employee_id']);$d+=['from_branch_id'=>$e->branch_id,'from_department_id'=>$e->department_id,'from_designation_id'=>$e->designation_id];unset($d['document']);if($r->hasFile('document')){if($t->document_path)Storage::disk('public')->delete($t->document_path);$d['document_path']=$r->file('document')->store('transfers','public');}DB::transaction(function()use($t,$d){$t->fill($d)->save();$this->applyIfApproved($t);});}
 private function applyIfApproved(EmployeeTransfer $t):void{if($t->status!=='Approved')return;$data=['branch_id'=>$t->to_branch_id,'department_id'=>$t->to_department_id,'designation_id'=>$t->to_designation_id,'branch'=>Branch::find($t->to_branch_id)?->name,'department'=>Department::find($t->to_department_id)?->name,'designation'=>Designation::find($t->to_designation_id)?->name];$t->employee()->update($data);}
}
