<?php
namespace App\Http\Controllers;
use App\Models\{Employee,EmployeeWarning,User};use Illuminate\Http\Request;use Illuminate\Support\Facades\Storage;
class WarningController extends Controller{
 const TYPES=['Attendance','Performance','Conduct','Policy Violation','Safety','Communication','Insubordination','Confidentiality'];
 public function __construct(){$this->middleware('auth');}
 public function index(Request $r){$q=EmployeeWarning::with(['employee','manager'])->latest('warning_date');$q->when($r->search,fn($q,$v)=>$q->where(fn($q)=>$q->where('subject','like',"%$v%")->orWhereHas('employee',fn($e)=>$e->where('name','like',"%$v%"))))->when($r->warning_type,fn($q,$v)=>$q->where('warning_type',$v))->when($r->severity,fn($q,$v)=>$q->where('severity',$v))->when($r->status&&$r->status!=='All',fn($q)=>$q->where('status',$r->status));$counts=['All'=>EmployeeWarning::count(),'Draft'=>EmployeeWarning::whereStatus('Draft')->count(),'Issued'=>EmployeeWarning::whereStatus('Issued')->count(),'Acknowledged'=>EmployeeWarning::whereStatus('Acknowledged')->count(),'Expired'=>EmployeeWarning::whereStatus('Expired')->count()];return view('warnings.index',['warnings'=>$q->paginate(10)->withQueryString(),'employees'=>Employee::where('employment_status','Active')->orderBy('name')->get(),'managers'=>User::where('status',1)->orderBy('first_name')->orderBy('last_name')->get(),'types'=>self::TYPES,'counts'=>$counts]);}
 public function store(Request $r){$this->save($r,new EmployeeWarning);return back()->with('success','Warning created successfully.');}
 public function update(Request $r,EmployeeWarning $warning){$this->save($r,$warning);return back()->with('success','Warning updated successfully.');}
 public function status(Request $r,EmployeeWarning $warning){$d=$r->validate(['status'=>'required|in:Draft,Issued,Acknowledged,Expired','acknowledgment_date'=>'required_if:status,Acknowledged|nullable|date','employee_response'=>'required_if:status,Acknowledged|nullable|string|max:2000']);$warning->update($d);return back()->with('success','Warning status updated.');}
 public function document(EmployeeWarning $warning){abort_unless($warning->document_path&&Storage::disk('public')->exists($warning->document_path),404);return Storage::disk('public')->response($warning->document_path);}
 public function destroy(EmployeeWarning $warning){if($warning->document_path)Storage::disk('public')->delete($warning->document_path);$warning->delete();return back()->with('success','Warning deleted successfully.');}
 private function save(Request $r,EmployeeWarning $w):void{$d=$r->validate(['employee_id'=>'required|exists:employees,id','warning_by'=>'required|exists:users,id','warning_type'=>'required|in:'.implode(',',self::TYPES),'subject'=>'required|string|max:191','severity'=>'required|in:Verbal,Written,Final','warning_date'=>'required|date','description'=>'nullable|string|max:3000','document'=>'nullable|file|mimes:pdf,jpg,jpeg,png,doc,docx|max:5120','expiry_date'=>'nullable|date|after_or_equal:warning_date','has_improvement_plan'=>'nullable|boolean','improvement_goals'=>'nullable|string|max:2000','improvement_start_date'=>'nullable|date','improvement_end_date'=>'nullable|date|after_or_equal:improvement_start_date','status'=>'required|in:Draft,Issued,Acknowledged,Expired']);$d['has_improvement_plan']=$r->boolean('has_improvement_plan');unset($d['document']);if($r->hasFile('document')){if($w->document_path)Storage::disk('public')->delete($w->document_path);$d['document_path']=$r->file('document')->store('warnings','public');}$w->fill($d)->save();}
}
