@extends('layouts.master')
@section('content')
<div class="toolbar" id="kt_toolbar"><div class="container-fluid d-flex flex-stack"><h1 class="text-dark fw-bolder fs-3">Employees <small class="text-muted fs-7 ms-2">Employee List</small></h1><a href="{{ route('add-employee') }}" class="btn btn-sm btn-success">Add Employee</a></div></div>
<div class="container-fluid py-6">@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="card mb-5"><div class="card-body pb-0"><form method="GET" class="row g-3 mb-5"><div class="col-md-4"><input name="search" value="{{ request('search') }}" class="form-control" placeholder="Search name, email or employee ID"></div><div class="col-md-3"><select name="department" class="form-select"><option value="">All Departments</option>@foreach($departments as $v)<option @selected(request('department')===$v)>{{ $v }}</option>@endforeach</select></div><div class="col-md-3"><select name="designation" class="form-select"><option value="">All Designations</option>@foreach($designations as $v)<option @selected(request('designation')===$v)>{{ $v }}</option>@endforeach</select></div><div class="col-md-2"><button class="btn btn-primary w-100">Filters</button></div></form><div class="d-flex gap-5 border-top pt-4">@foreach($counts as $status=>$count)<a class="pb-3 fw-bold {{ request('status','All')===$status?'text-success border-bottom border-success border-3':'text-muted' }}" href="{{ route('employee-list',array_filter(request()->except(['page','status'])+($status==='All'?[]:['status'=>$status]))) }}">{{ $status }} <span class="badge badge-light">{{ $count }}</span></a>@endforeach</div></div></div>
<div class="card"><div class="card-body p-0"><div class="table-responsive"><table class="table table-row-bordered align-middle mb-0"><thead class="bg-light"><tr><th class="ps-5">#</th><th>Name</th><th>Employee ID</th><th>Department</th><th>Designation</th><th>Employee Status</th><th>Joined</th><th>Login Status</th><th>Actions</th></tr></thead><tbody>
@forelse($employees as $employee)<tr><td class="ps-5">{{ $employees->firstItem()+$loop->index }}</td><td><strong>{{ $employee->name }}</strong><div class="text-muted">{{ $employee->email }}</div></td><td><span class="badge badge-light-primary">{{ $employee->employee_code }}</span></td><td>{{ $employee->department }}</td><td>{{ $employee->designation }}</td><td><span class="badge badge-light-{{ $employee->employment_status==='Active'?'success':'warning' }}">{{ $employee->employment_status }}</span></td><td>{{ $employee->date_of_joining?->format('Y-m-d') }}</td><td><span class="badge badge-light-{{ $employee->login_status?'success':'danger' }}">{{ $employee->login_status?'Active':'Inactive' }}</span></td><td><div class="d-flex gap-2"><a href="{{ route('employee-edit',$employee) }}" class="btn btn-sm btn-light-primary">Edit</a><form method="POST" action="{{ route('employee-delete',$employee) }}" onsubmit="return confirm('Delete this employee?')">@csrf @method('DELETE')<button class="btn btn-sm btn-light-danger">Delete</button></form></div></td></tr>@empty<tr><td colspan="9" class="text-center py-10 text-muted">No employees found.</td></tr>@endforelse
</tbody></table></div></div></div><div class="mt-5">{{ $employees->links() }}</div></div>
@endsection
