@extends('layouts.master')
@section('content')
<style>.employee-actions{display:flex;align-items:center;gap:10px}.employee-action{border:0;background:transparent;padding:2px;color:#78849a;line-height:1}.employee-action:hover{color:#11b981}.employee-action svg{width:18px;height:18px;stroke:currentColor;fill:none;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}</style>
<div class="toolbar" id="kt_toolbar"><div class="container-fluid d-flex flex-stack"><h1 class="text-dark fw-bolder fs-3">Employees <small class="text-muted fs-7 ms-2">Employee List</small></h1><a href="{{ route('add-employee') }}" class="btn btn-sm btn-success">Add Employee</a></div></div>
<div class="container-fluid py-6">@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif @if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="card mb-5"><div class="card-body pb-0"><form method="GET" class="row g-3 mb-5"><div class="col-md-3"><input name="search" value="{{ request('search') }}" class="form-control" placeholder="Search name, email or employee ID"></div>@foreach(['branch_id'=>['All Branches',$branches],'department_id'=>['All Departments',$departments],'designation_id'=>['All Designations',$designations]] as $key=>$meta)<div class="col-md-2"><select name="{{ $key }}" class="form-select"><option value="">{{ $meta[0] }}</option>@foreach($meta[1] as $v)<option value="{{ $v->id }}" @selected(request($key)==$v->id)>{{ $v->name }}</option>@endforeach</select></div>@endforeach<div class="col-md-2 d-flex gap-2"><button class="btn btn-primary flex-grow-1">Filters</button>@if(request()->hasAny(['search','branch_id','department_id','designation_id','status']))<a href="{{ route('employee-list') }}" class="btn btn-light-danger text-nowrap" title="Clear all filters">Clear</a>@endif</div></form><div class="d-flex gap-5 border-top pt-4">@foreach($counts as $status=>$count)<a class="pb-3 fw-bold {{ request('status','All')===$status?'text-success border-bottom border-success border-3':'text-muted' }}" href="{{ route('employee-list',array_filter(request()->except(['page','status'])+($status==='All'?[]:['status'=>$status]))) }}">{{ $status }} <span class="badge badge-light">{{ $count }}</span></a>@endforeach</div></div></div>
<div class="card"><div class="card-body p-0"><div class="table-responsive"><table class="table table-row-bordered align-middle mb-0"><thead class="bg-light"><tr><th class="ps-5">#</th><th>Name</th><th>Employee ID</th><th>Department</th><th>Designation</th><th>Employee Status</th><th>Joined</th><th>Login Status</th><th>Actions</th></tr></thead><tbody>
@forelse($employees as $employee)<tr><td class="ps-5">{{ $employees->firstItem()+$loop->index }}</td><td><strong>{{ $employee->name }}</strong><div class="text-muted">{{ $employee->email }}</div></td><td><span class="badge badge-light-primary">{{ $employee->employee_code }}</span></td><td>{{ $departments->firstWhere('id',$employee->department_id)->name??$employee->department??'—' }}</td><td>{{ $designations->firstWhere('id',$employee->designation_id)->name??$employee->designation??'—' }}</td><td><span class="badge badge-light-{{ $employee->employment_status==='Active'?'success':'warning' }}">{{ $employee->employment_status }}</span></td><td>{{ $employee->date_of_joining?->format('Y-m-d') }}</td><td><span class="badge badge-light-{{ $employee->login_status?'success':'danger' }}">{{ $employee->login_status?'Active':'Inactive' }}</span></td><td><div class="employee-actions"><a class="employee-action" href="{{ route('employee-show',$employee) }}" title="View"><svg viewBox="0 0 24 24"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z"/><circle cx="12" cy="12" r="2.5"/></svg></a><a class="employee-action" href="{{ route('employee-edit',$employee) }}" title="Edit"><svg viewBox="0 0 24 24"><path d="M12 20H5a1 1 0 0 1-1-1v-7"/><path d="m16.5 3.5 4 4L11 17l-5 1 1-5Z"/><path d="m14 6 4 4"/></svg></a><button type="button" class="employee-action js-password" title="Change Password" data-bs-toggle="modal" data-bs-target="#passwordModal" data-url="{{ route('employee-password',$employee) }}" data-name="{{ $employee->name }}"><svg viewBox="0 0 24 24"><circle cx="8" cy="15" r="4"/><path d="m11 12 8-8m-2 2 2 2m-5 1 2 2"/></svg></button><form method="POST" action="{{ route('employee-toggle-status',$employee) }}" onsubmit="return confirm('{{ $employee->login_status?'Deactivate':'Activate' }} this employee login?')">@csrf @method('PATCH')<button class="employee-action" title="{{ $employee->login_status?'Deactivate':'Activate' }} Login"><svg viewBox="0 0 24 24"><rect x="5" y="10" width="14" height="10" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></svg></button></form><form method="POST" action="{{ route('employee-delete',$employee) }}" onsubmit="return confirm('Delete this employee?')">@csrf @method('DELETE')<button class="employee-action" title="Delete"><svg viewBox="0 0 24 24"><path d="M3 6h18M8 6V4h8v2m3 0-1 15H6L5 6m5 4v7m4-7v7"/></svg></button></form></div></td></tr>@empty<tr><td colspan="9" class="text-center py-10 text-muted">No employees found.</td></tr>@endforelse
</tbody></table></div></div></div><div class="mt-5">{{ $employees->links() }}</div></div>
<div class="modal fade" id="passwordModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form id="passwordForm" method="POST">@csrf @method('PATCH')<div class="modal-header"><h5 class="modal-title">Change Password — <span id="passwordEmployee"></span></h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label required">New Password</label><div class="input-group mb-4"><input id="newPassword" name="password" type="password" class="form-control" required minlength="6" maxlength="72" pattern="[0-9]{6,}" inputmode="numeric"><button class="btn btn-light js-eye" type="button" data-target="newPassword">Show</button></div><label class="form-label required">Confirm Password</label><div class="input-group"><input id="confirmPassword" name="password_confirmation" type="password" class="form-control" required minlength="6" maxlength="72" pattern="[0-9]{6,}" inputmode="numeric"><button class="btn btn-light js-eye" type="button" data-target="confirmPassword">Show</button></div><div class="form-text">Minimum 6 digits; numbers only.</div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button class="btn btn-success">Change Password</button></div></form></div></div></div>
<script>document.addEventListener('DOMContentLoaded',function(){document.querySelectorAll('.js-password').forEach(function(b){b.addEventListener('click',function(){document.getElementById('passwordForm').action=b.dataset.url;document.getElementById('passwordEmployee').textContent=b.dataset.name;document.getElementById('passwordForm').reset();});});document.querySelectorAll('.js-eye').forEach(function(b){b.addEventListener('click',function(){var i=document.getElementById(b.dataset.target),show=i.type==='password';i.type=show?'text':'password';b.textContent=show?'Hide':'Show';});});});</script>
<script>
document.addEventListener('DOMContentLoaded',function(){
 document.querySelectorAll('form[action*="toggle-status"],form[action*="employee-delete"]').forEach(function(form){
  form.onsubmit=null;
  form.addEventListener('submit',function(event){
   if(form.dataset.confirmed==='1')return;
   event.preventDefault();
   var deleting=form.action.indexOf('employee-delete')!==-1;
   var activating=!deleting&&form.closest('tr').querySelector('td:nth-child(8)').textContent.trim()==='Inactive';
   Swal.fire({
    title:deleting?'Delete employee?':(activating?'Activate employee login?':'Deactivate employee login?'),
    text:deleting?'This employee and related records will be permanently deleted.':(activating?'The employee will be able to log in again.':'The employee will no longer be able to log in.'),
    icon:'warning',showCancelButton:true,buttonsStyling:false,
    confirmButtonText:deleting?'Yes, delete':'Yes, continue',cancelButtonText:'Cancel',
    customClass:{confirmButton:'btn '+(deleting?'btn-danger':'btn-success'),cancelButton:'btn btn-light ms-3'}
   }).then(function(result){if(result.isConfirmed||result.value){form.dataset.confirmed='1';form.submit();}});
  });
 });
});
</script>
@endsection
