@extends('layouts.master')
@section('content')
@php($display=fn($value)=>filled($value)?$value:'—')
@php($certifications=$employee->documents->filter(fn($doc)=>preg_match('/certificate|certification|joining|noc|letter/i',$doc->type?->name??'')))
<style>
.employee-shell{background:#f7f9fc;border:1px solid #e4e8ef;border-radius:12px;padding:24px}.employee-profile,.employee-pane{background:#fff;border:1px solid #e1e5eb;border-radius:10px;box-shadow:0 2px 4px rgba(0,0,0,.04)}.employee-profile{padding:24px}.employee-avatar{width:126px;height:126px;border-radius:50%;object-fit:cover;background:#edf1f7}.employee-avatar-fallback{display:flex;align-items:center;justify-content:center;margin:auto;font-size:38px;font-weight:700}.employee-summary{list-style:none;padding:0;margin:28px 0 0}.employee-summary li{margin:13px 0;color:#27364b}.employee-tabs{display:flex;background:#f2f3f5;border-radius:8px;padding:3px}.employee-tab{flex:1;border:0;background:transparent;padding:10px;border-radius:7px;color:#667085;font-weight:600}.employee-tab.active{background:#fff;color:#111;box-shadow:0 1px 4px rgba(0,0,0,.12)}.employee-pane{display:none;padding:25px;margin-top:16px;min-height:310px}.employee-pane.active{display:block}.detail-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:22px 50px}.detail-label{color:#78849a;font-size:13px;margin-bottom:4px}.detail-value{font-weight:600;color:#172033}.document-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.document-card{border:1px solid #e1e5eb;border-radius:9px;padding:18px;display:flex;justify-content:space-between;align-items:center;gap:15px}@media(max-width:991px){.detail-grid,.document-grid{grid-template-columns:1fr}.employee-tabs{overflow:auto}.employee-tab{min-width:130px}}
</style>
<div class="toolbar"><div class="container-fluid d-flex justify-content-between align-items-center"><div><h1 class="fs-3 fw-bolder mb-1">{{ $employee->name }}</h1><span class="text-muted">View detailed information and activity for employee.</span></div><a href="{{ route('employee-list') }}" class="btn btn-sm btn-light">← Back</a></div></div>
<div class="container-fluid py-6"><div class="employee-shell"><div class="row g-6"><div class="col-xl-3"><aside class="employee-profile text-center">@if($employee->profile_image)<img class="employee-avatar" src="{{ route('employee-profile',$employee) }}" alt="{{ $employee->name }}">@else<div class="employee-avatar employee-avatar-fallback">{{ strtoupper(substr($employee->name,0,1)) }}</div>@endif<h2 class="fs-3 mt-5 mb-2">{{ $employee->name }}</h2><div class="text-muted">{{ $display($designation?->name??$employee->designation) }}</div><span class="badge badge-light-{{ $employee->employment_status==='Active'?'success':'warning' }} mt-3">{{ $employee->employment_status }}</span><ul class="employee-summary text-start"><li>Employee ID: {{ $employee->employee_code }}</li><li>✉ {{ $employee->email }}</li><li>☎ {{ $employee->phone }}</li><li>DOB: {{ $employee->date_of_birth?->format('Y-m-d')??'—' }}</li><li>Joined: {{ $employee->date_of_joining?->format('Y-m-d')??'—' }}</li><li>{{ $display($department?->name??$employee->department) }}</li><li>{{ $display($branch?->name??$employee->branch) }}</li><li>{{ $display($employee->employment_type) }}</li></ul></aside></div>
<div class="col-xl-9"><nav class="employee-tabs">@foreach(['basic'=>'Basic Info','employment'=>'Employment','contact'=>'Contact','banking'=>'Banking','certifications'=>'Certifications','documents'=>'Documents'] as $id=>$label)<button type="button" class="employee-tab {{ $loop->first?'active':'' }}" data-pane="{{ $id }}">{{ $label }}</button>@endforeach</nav>
@php($sections=[
'basic'=>['Basic Information',['Full Name'=>$employee->name,'Employee ID'=>$employee->employee_code,'Email'=>$employee->email,'Phone Number'=>$employee->phone,'Employee Code'=>$employee->biometric_code,'Date of Birth'=>$employee->date_of_birth?->format('Y-m-d'),'Gender'=>$employee->gender]],
'employment'=>['Employment Details',['Branch'=>$branch?->name??$employee->branch,'Department'=>$department?->name??$employee->department,'Designation'=>$designation?->name??$employee->designation,'Date of Joining'=>$employee->date_of_joining?->format('Y-m-d'),'Employment Type'=>$employee->employment_type,'Employee Status'=>$employee->employment_status,'Shift'=>$shift?($shift->name.' ('.substr($shift->start_time,0,5).' - '.substr($shift->end_time,0,5).')'):null,'Attendance Policy'=>$policy?->name]],
'banking'=>['Banking Information',['Bank Name'=>$employee->bank_name,'Account Holder Name'=>$employee->account_holder_name,'Account Number'=>$employee->account_number,'Bank Identifier Code (BIC/SWIFT)'=>$employee->bank_identifier_code,'Bank Branch'=>$employee->bank_branch,'Tax Payer ID'=>$employee->tax_id,'Base Salary'=>$employee->base_salary!==null?number_format((float)$employee->base_salary,2):null]]])
@foreach($sections as $key=>$section)<section id="pane-{{ $key }}" class="employee-pane {{ $loop->first?'active':'' }}"><h2 class="fs-4 mb-7">{{ $section[0] }}</h2><div class="detail-grid">@foreach($section[1] as $label=>$value)<div><div class="detail-label">{{ $label }}</div><div class="detail-value">{{ $display($value) }}</div></div>@endforeach</div></section>@endforeach
<section id="pane-contact" class="employee-pane"><h2 class="fs-4 mb-7">Contact Information</h2><div class="detail-grid">@foreach(['Address Line 1'=>$employee->address_line_1,'Address Line 2'=>$employee->address_line_2,'City'=>$employee->city,'State/Province'=>$employee->state,'Country'=>$employee->country,'Postal/Zip Code'=>$employee->postal_code] as $label=>$value)<div><div class="detail-label">{{ $label }}</div><div class="detail-value">{{ $display($value) }}</div></div>@endforeach</div><h2 class="fs-4 my-7">Emergency Contact</h2><div class="detail-grid">@foreach(['Name'=>$employee->emergency_contact_name,'Relationship'=>$employee->emergency_contact_relationship,'Phone Number'=>$employee->emergency_contact_phone] as $label=>$value)<div><div class="detail-label">{{ $label }}</div><div class="detail-value">{{ $display($value) }}</div></div>@endforeach</div></section>
<section id="pane-certifications" class="employee-pane"><h2 class="fs-4 mb-7">Employee Certifications</h2><div class="document-grid">@forelse($certifications as $document)<div class="document-card"><div><strong>{{ $document->type?->name??'Certification' }}</strong><div class="text-muted">{{ $document->type?->description??'Employee certification document' }}</div></div><a class="btn btn-sm btn-light" href="{{ route('employee-document-download',$document) }}">Download</a></div>@empty<div class="text-muted">No certification documents found.</div>@endforelse</div></section>
<section id="pane-documents" class="employee-pane"><h2 class="fs-4 mb-7">Documents</h2><div class="document-grid">@forelse($employee->documents as $document)<div class="document-card"><div><strong>{{ $document->type?->name??'Document' }}</strong><div class="text-muted">{{ $document->expiry_date?'Expiry: '.$document->expiry_date->format('Y-m-d'):'No expiry date' }}</div></div><a class="btn btn-sm btn-light" href="{{ route('employee-document-download',$document) }}">View / Download</a></div>@empty<div class="text-muted">No documents found.</div>@endforelse</div></section>
</div></div></div></div>
<script>document.addEventListener('DOMContentLoaded',function(){var tabs=document.querySelectorAll('.employee-tab'),panes=document.querySelectorAll('.employee-pane');tabs.forEach(function(tab){tab.addEventListener('click',function(){tabs.forEach(function(item){item.classList.remove('active')});panes.forEach(function(pane){pane.classList.remove('active')});tab.classList.add('active');document.getElementById('pane-'+tab.dataset.pane).classList.add('active');});});});</script>
@endsection
